from uuid import UUID
from typing import Dict, Any, Optional

from pydantic import BaseModel, HttpUrl

class QRCodeBase(BaseModel):
    asset_id: UUID

class QRCodeCreate(QRCodeBase):
    # No extra fields needed for creation, asset_id is enough
    # QR content and URL are generated by the service
    pass

class QRCodeRead(QRCodeBase):
    id: UUID
    qr_url: str # This could be a base64 encoded image or a URL to an image file
    payload: Dict[str, Any] # The data embedded in the QR code

    class Config:
        from_attributes = True
# Update AssetRead schema (this file is app/schemas/qr.py, so this is for reference)
# In app/schemas/asset.py, AssetRead should be updated to include:
# qr_code: Optional[QRCodeRead] = None
# This will be handled in a separate step when updating asset.py.
