services:
  - type: web
    name: scanly
    runtime: python
    buildCommand: ""
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: ./
